"""modifica categoria obrigatorio

Revision ID: 5881a4b18ce2
Revises: a75bc6e9f766
Create Date: 2026-01-07 14:26:05.884629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5881a4b18ce2'
down_revision: Union[str, Sequence[str], None] = 'a75bc6e9f766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'category',
               existing_type=postgresql.ENUM('ALIMENTACAO', 'ASSINATURA', 'TRANSPORTE', 'LAZER', 'SAUDE', 'OUTROS', name='transactioncategory'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'category',
               existing_type=postgresql.ENUM('ALIMENTACAO', 'ASSINATURA', 'TRANSPORTE', 'LAZER', 'SAUDE', 'OUTROS', name='transactioncategory'),
               nullable=True)
    # ### end Alembic commands ###
