"""cria_tabelas_monthly_budgets

Revision ID: 8a9c1d55f019
Revises: df4b33ab4ff3
Create Date: 2026-03-20 04:08:20.732466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a9c1d55f019'
down_revision: Union[str, Sequence[str], None] = 'df4b33ab4ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE transactioncategory ADD VALUE IF NOT EXISTS 'INVESTIMENTOS'"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('income_used', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column(
        'methodology_used',
        postgresql.ENUM(
            'FIFTY_THIRTY_TWENTY',
            'SIXTY_TWENTY_TWENTY',
            'SIXTY_THIRTY_TEN',
            name='budgetmethodology',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['budget_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_only_one_budget_per_user_in_a_month')
    )
    op.create_table('monthly_budget_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monthly_budget_id', sa.UUID(), nullable=False),
    sa.Column(
        'category',
        postgresql.ENUM(
            'ALIMENTACAO',
            'ASSINATURA',
            'TRANSPORTE',
            'LAZER',
            'SAUDE',
            'INVESTIMENTOS',
            'OUTROS',
            name='transactioncategory',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('budget_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bucket', sa.Enum('NEEDS', 'WANTS', 'SAVINGS', name='budgetbucket'), nullable=False),
    sa.ForeignKeyConstraint(['monthly_budget_id'], ['monthly_budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_budget_categories')
    op.drop_table('monthly_budgets')
    op.execute('DROP TYPE budgetbucket')

    conn = op.get_bind()
    count = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM transactions WHERE category = 'INVESTIMENTOS'"
        )
    ).scalar_one()
    if count:
        raise RuntimeError(
            "Nao e possivel fazer downgrade: existem transacoes com "
            "category='INVESTIMENTOS'."
        )
    op.execute("ALTER TYPE transactioncategory RENAME TO transactioncategory_old")
    op.execute(
        "CREATE TYPE transactioncategory AS ENUM "
        "('ALIMENTACAO', 'ASSINATURA', 'TRANSPORTE', 'LAZER', 'SAUDE', 'OUTROS')"
    )
    op.execute(
        "ALTER TABLE transactions "
        "ALTER COLUMN category TYPE transactioncategory "
        "USING category::text::transactioncategory"
    )
    op.execute("DROP TYPE transactioncategory_old")
    # ### end Alembic commands ###
