"""Coloca index na categoria da tabela transactions

Revision ID: a75bc6e9f766
Revises: d592a797e1bb
Create Date: 2026-01-04 20:11:26.979732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75bc6e9f766'
down_revision: Union[str, Sequence[str], None] = 'd592a797e1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    # ### end Alembic commands ###
