"""cria_tabela_budget_templates

Revision ID: df4b33ab4ff3
Revises: 5881a4b18ce2
Create Date: 2026-02-22 02:37:45.439339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4b33ab4ff3'
down_revision: Union[str, Sequence[str], None] = '5881a4b18ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('methodology', sa.Enum('FIFTY_THIRTY_TWENTY', 'SIXTY_TWENTY_TWENTY', 'SIXTY_THIRTY_TEN', name='budgetmethodology'), nullable=False),
    sa.Column('default_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_templates')
    op.execute('DROP TYPE budgetmethodology')
    # ### end Alembic commands ###
